# Generated by Django 4.2.7 on 2025-01-07 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('fin', models.CharField(max_length=7, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='agent_photos/')),
                ('status', models.CharField(choices=[('Passed to Interview', 'Passed to Interview'), ('Failed to Interview', 'Failed to Interview'), ('Invited to Training', 'Invited to Training'), ('Failed to Training', 'Failed to Training'), ('Passed to Training', 'Passed to Training'), ('Invited to Work', 'Invited to Work'), ('Failed to Work', 'Failed to Work'), ('Working', 'Working'), ('Left', 'Left')], default='Passed to Interview', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icbari_1', models.IntegerField(blank=True, null=True)),
                ('icbari_2', models.FloatField(blank=True, null=True)),
                ('konullu_1', models.IntegerField(blank=True, null=True)),
                ('konullu_2', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='manager_photos/')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.department')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(blank=True, related_name='groups', to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='department_head_photos/')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agents.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.department'),
        ),
        migrations.AddField(
            model_name='agent',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.group'),
        ),
        migrations.AddField(
            model_name='agent',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.manager'),
        ),
        migrations.CreateModel(
            name='AgentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('schedule_type', models.CharField(choices=[('i', 'i/e'), ('qb', 'qb')], max_length=2)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
            ],
            options={
                'unique_together': {('agent', 'date')},
            },
        ),
    ]
