# Generated by Django 4.1.2 on 2024-12-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
