# Generated by Django 4.2.7 on 2025-01-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='department_transfer_date',
            field=models.DateField(blank=True, help_text='Date when agent was transferred to department', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='training_period',
            field=models.JSONField(blank=True, help_text='Training period start and end dates in format {"start": "YYYY-MM-DD", "end": "YYYY-MM-DD"}', null=True),
        ),
    ]
