# Generated by Django 4.2.7 on 2025-01-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_department_transfer_date_agent_training_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('Passed to Interview', 'Passed to Interview'), ("Didn't Come to Training", "Didn't Come to Training"), ('Failed to Interview', 'Failed to Interview'), ('Failed to Training', 'Failed to Training'), ('Passed to Training', 'Passed to Training'), ("Didn't Come to Work", "Didn't Come to Work"), ('Invited to Work', 'Invited to Work'), ('Failed to Work', 'Failed to Work'), ('Working', 'Working'), ('Left', 'Left')], default='Passed to Interview', max_length=50),
        ),
    ]
