# Generated by Django 4.2.7 on 2025-01-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_agent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('Passed to Interview', 'Passed to Interview'), ('Invited to Training', 'Invited to Training'), ("Didn't Come to Training", "Didn't Come to Training"), ('Failed to Training', 'Failed to Training'), ('Passed to Training', 'Passed to Training'), ("Didn't Come to Work", "Didn't Come to Work"), ('Invited to Work', 'Invited to Work'), ('Failed to Work', 'Failed to Work')], default='Passed to Interview', max_length=50),
        ),
    ]
