# Generated by Django 4.2.7 on 2025-01-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_alter_agent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('Müsahibədən keçdi', 'Müsahibədən keçdi'), ('Təlimə dəvət oldu', 'Təlimə dəvət oldu'), ('Təlimə gəlmədi', 'Təlimə gəlmədi'), ('Təlimi keçə bilmədi', 'Təlimi keçə bilmədi'), ('Təlimdən keçdi', 'Təlimdən keçdi'), ('İşə gəlmədi', 'İşə gəlmədi'), ('İşə dəvət olundu', 'İşə dəvət olundu'), ('İşdən çıxdı', 'İşdən çıxdı')], default='Müsahibədən keçdi', max_length=50),
        ),
    ]
