# Generated by Django 4.1.2 on 2024-12-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_manager_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
